### ISSUE TITLE
Send collaboration message

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-blog#13]
As a **potential collaborator** I can **send a message to the site admin** so that **I can propose a collaboration**

### Acceptance criteria

1. I can click a link to send a message
2. I can add my name and email along with a message
3. My message gets to the administrator

### Tasks

- [ ] Create collaboration form
- [ ] Link to the form
- [ ] Make the form send the message
